#!/usr/bin/env bash
# EPA Compliance Dashboard - Staging Environment Setup
# Usage: bash setup-staging-env.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_ENV_FILE="$ROOT_DIR/apps/api/.env"
WEB_ENV_FILE="$ROOT_DIR/apps/web/.env.staging"

echo "=============================================="
echo "EPA Compliance Dashboard - Staging Setup"
echo "=============================================="
echo

DEFAULT_JWT_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"

read -rp "Staging web domain (e.g. staging.example.com): " STAGING_WEB_DOMAIN
if [[ -z "${STAGING_WEB_DOMAIN}" ]]; then
  echo "Error: staging web domain is required."
  exit 1
fi

read -rp "Staging API domain (e.g. staging-api.example.com): " STAGING_API_DOMAIN
if [[ -z "${STAGING_API_DOMAIN}" ]]; then
  echo "Error: staging API domain is required."
  exit 1
fi

read -rp "MongoDB URI: " MONGO_URI
if [[ -z "${MONGO_URI}" ]]; then
  echo "Error: MongoDB URI is required."
  exit 1
fi

read -rp "JWT secret (leave empty to auto-generate): " JWT_SECRET
JWT_SECRET="${JWT_SECRET:-$DEFAULT_JWT_SECRET}"

read -rsp "Admin password: " ADMIN_PASSWORD
echo
if [[ -z "${ADMIN_PASSWORD}" ]]; then
  echo "Error: admin password is required."
  exit 1
fi

read -rp "Admin email [admin-staging@${STAGING_WEB_DOMAIN}]: " ADMIN_EMAIL
ADMIN_EMAIL="${ADMIN_EMAIL:-admin-staging@${STAGING_WEB_DOMAIN}}"

read -rp "Admin full name [Staging Administrator]: " ADMIN_NAME
ADMIN_NAME="${ADMIN_NAME:-Staging Administrator}"

read -rp "Admin CNIC [staging-admin-cnic]: " ADMIN_CNIC
ADMIN_CNIC="${ADMIN_CNIC:-staging-admin-cnic}"

read -rp "Resend API key (re_...): " RESEND_API_KEY
if [[ -z "${RESEND_API_KEY}" ]]; then
  echo "Error: Resend API key is required."
  exit 1
fi

read -rp "Resend sender email [onboarding@resend.dev]: " EMAIL_FROM
EMAIL_FROM="${EMAIL_FROM:-onboarding@resend.dev}"

read -rp "Resend sender name [EPA Compliance Dashboard (Staging)]: " EMAIL_FROM_NAME
EMAIL_FROM_NAME="${EMAIL_FROM_NAME:-EPA Compliance Dashboard (Staging)}"

cat > "${API_ENV_FILE}" <<EOF
# Auto-generated by setup-staging-env.sh
NODE_ENV=production
PORT=4000
MONGO_URI=${MONGO_URI}
JWT_SECRET=${JWT_SECRET}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_NAME=${ADMIN_NAME}
ADMIN_CNIC=${ADMIN_CNIC}
CORS_ORIGIN=https://${STAGING_WEB_DOMAIN}
PUBLIC_BASE_URL=https://${STAGING_API_DOMAIN}
APP_BASE_URL=https://${STAGING_WEB_DOMAIN}
UPLOAD_DIR=./uploads
SECURE_UPLOADS_DIR=../secure-uploads
RESEND_API_KEY=${RESEND_API_KEY}
EMAIL_FROM=${EMAIL_FROM}
EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
EOF

chmod 600 "${API_ENV_FILE}"

cat > "${WEB_ENV_FILE}" <<EOF
# Auto-generated by setup-staging-env.sh
VITE_API_URL=https://${STAGING_API_DOMAIN}
EOF

echo
echo "Created:"
echo "  - ${API_ENV_FILE}"
echo "  - ${WEB_ENV_FILE}"
echo
echo "Next steps:"
echo "  1) npm install"
echo "  2) npm --prefix apps/web run build -- --mode staging"
echo "  3) npm --prefix apps/api run start"
